# Generated by Django 4.1.1 on 2022-10-26 08:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Carhire', '0002_car_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_date', models.DateField(auto_now=True)),
                ('car', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Carhire.car')),
            ],
        ),
    ]
