# Generated by Django 4.1.1 on 2022-10-26 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carhire', '0004_alter_booking_hire_date_alter_booking_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='availability',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='rates_per_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Carhire.car'),
        ),
    ]
