# Generated by Django 4.1.1 on 2022-10-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carhire', '0005_car_availability_car_rates_per_day_alter_booking_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
